### ISSUE TITLE
ResealTimer::set_min_timer causes a crash

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1069]
I found that `reseal_timer.schedule_once` in the `ResealTimer::set_min_timer` causes crash.
I suspect that the cause of the crash is https://github.com/CodeChain-io/codechain/pull/1041 's modification.

@sgkim126 @foriequal0 
How about adding an atomic version of `cancle_and_schedule_once`?

**Comment by sgkim126** [comment]
@foriequal0 
I have three questions.
1. Is the order of schedule and cancel in the same thread guaranteed?
2. What happens if the scheduled token is scheduled again.
3. What happens if the canceled token is canceled again.

**Comment by foriequal0** [comment]
@sgkim126

1. Yes
  `Schedule::schedule` function puts a `ScheduleStateControl` to the `SchedulerInner` (with lock), and `Schedule::cancel` function finds `ScheduleStateControl` from it, and it should be sequential. But even if it succeeds to fire cancel signal, it can race with on_timeout scheduling (callback could be called)

2. Before the token is expired, it should return Err(TokenAlreadyScheduled), otherwise, it should succeed.

3. It just returns `false`.

**Comment by sgkim126** [comment]
@majecty I discussed with @foriequal0 
IMO, the atomic `cancle_and_schedule_once` works in the same if
1. the order in the same transaction is guaranteed
2. it's okay to schedule already scheduled token
3. it's okay to cancel already canceled token
And currently, the only error returned by `schedule_once` is `AlreadyScheduled`.
So I think it's okay if you just ignore the error of `schedule_once` function.

**Comment by majecty** [comment]
OK, I'll fix it by ignoring AlreadyScheduled error.
