### ISSUE TITLE
Need an RPC to get pending transactions in future queue.

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1383]
Currently, `mempool_getPendingTransactions` returns the transaction in the current queue only.

**Comment by MSNTCS** [comment]
We can easily do the same procedure used to get pending transactions in the current queue except calling ``` top-transaction``` in ```core/miner/mem-pool.rs ```. Instead, we should call ```future_transactions``` of the same class and update ```rpc/traits/mempool.rs ```.

**Comment by joojis** [comment]
@MSNTCS Sounds good to me.

I think there are 2 approaches to get transactions in the future queue when it comes to the interface design.

1. Change the `mempool_getPendingTransactions` by adding a parameter that makes the response **include** the future transactions along with the current transactions.

2. Add another JSON-RPC call that returns **only** future transactions.

I prefer the first one because I hadn't needed future transactions separately when I develop the applications.

Any thoughts? @sgkim126 @majecty @Remagpie

**Comment by majecty** [comment]
I also like the first one. The all the transactions in the current pool and future pool are pending transactions.

**Comment by Remagpie** [comment]
1st option LGTM too.

**Comment by sgkim126** [comment]
:+1: for the first approach.

**Comment by kseo** [comment]
Landed in bc42938614701bb2bc4346fab6d552f91295139e and 4934e9a6f87cb8006d7fe275335c128c5aa51115
