### ISSUE TITLE
getTransactionByTracker RPC doesn't return WrapCCC transactions 

### ISSUE THREAD

**Issue by Kais-DkM** [CodeChain-io/codechain#1547]
Indexer reports that an [AssetTransfer transaction](https://corgi.codechain.io/explorer/tx/0x9772d8a7785a9395b9c28aaf53d11c0e86bb1b078ef81c07ee970e830e8aaf43) spent a [WrapCCC transaction](https://corgi.codechain.io/explorer/tx/0x71765bbdedf9e22bcb053c41ce5a66852508ca4d0b066d0e943800c7e4719c32), but CodeChain returns null when `getTransactionByTracker` RPC is requested with the WrapCCC transaction's tracker.

You can try the request with the following command:
`curl https://corgi-rpc.codechain.io -H 'Content-Type: application/json'     -d '{"jsonrpc": "2.0", "method": "chain_getTransactionByTracker", "params": ["0x033e49e6e7eeb612694eedfd2b6274c4f0d5b21ce866710c02b4fb8c62f9572b"], "id": null}'`

**Comment by HoOngEe** [comment]
Current implementation stores (tracker, transactionAddress) into `body_db` only for `AssetTransaction`. Because `AssetTransaction` does not include `WrapCCC`, the `WrapCCC` transaction cannot be tracked back from the corresponding `tracker`.
After the patch, existing blocks should be re-synced to apply the correct tracking function.

**Comment by sgkim126** [comment]
Fixed by https://github.com/CodeChain-io/codechain/pull/1548
